language: objective-c
osx_image: xcode8.2
script: xcodebuild test -project Constraid.xcodeproj -scheme Constraid-iOS -sdk iphonesimulator -destination "OS=10.1,name=iPhone 7"
notifications:
  webhooks:
    urls:
        - https://webhooks.gitter.im/e/e85e44f40d1363636a7a
    on_success: change
    on_failure: always
    on_start: never
